In [1]:
import requests

ollama_api = "http://localhost:11434/api/generate"

In [2]:
# requests.post("http://localhost:11434/api/pull", json={"model": "glm-4.7-flash"})
# requests.post("http://localhost:11434/api/pull", json={"model": "qwen3:1.7b"})

In [4]:
res = requests.post(
    ollama_api,
    json={
        "model": "qwen2.5:14b",
        "prompt": "hi! I have the following text snippet: 'The sky is blue'. Please answer with only a literal 'yes' or 'no': does the snippet refer to any color?",
        "think": False,
        "stream": False,
    },
)
res.status_code

200

In [5]:
res.json()["response"]

'yes'

In [3]:
import pandas as pd

laion_metadata = pd.read_csv("/home/jp/mgr2024/freesound_meta.csv")
laion_metadata

,audio_filename,caption1,caption2,freesound_id,username,freesound_url,license
0,train/91671.flac,small group laugh 6.,A group of about twenty people laughing during...,30043,tim.kahn,https://freesound.org/s/30043/,https://creativecommons.org/licenses/by/4.0/
1,train/102050.flac,mushroom disco 2.,weird loop.,103163,fons,https://freesound.org/s/103163/,http://creativecommons.org/publicdomain/zero/1.0/
2,train/247195.flac,Page Turn 24.,31/36 of Various Book manipulations.,20258,Koops,https://freesound.org/s/20258/,https://creativecommons.org/licenses/by/4.0/
3,train/352235.flac,yawn soft.,Recording of a male yawn with a zoom H6 in a s...,404384,EskimoNeil,https://freesound.org/s/404384/,http://creativecommons.org/licenses/by-nc/3.0/
4,train/457574.flac,Fender Chroma Polaris - Mourning - D5 (Mournin...,Single note sampled from an analog synthesizer...,289166,modularsamples,https://freesound.org/s/289166/,http://creativecommons.org/publicdomain/zero/1.0/
...,...,...,...,...,...,...,...
516882,test/464571.flac,Eastbay-C-504R.,"Made with music program, fun to do;).",319481,visual,https://freesound.org/s/319481/,https://creativecommons.org/licenses/by/4.0/
516883,test/474610.flac,amazed 0 30q.,Typical movie-sound to provide the short momen...,136402,Setuniman,https://freesound.org/s/136402/,https://creativecommons.org/licenses/by-nc/4.0/
516884,test/499425.flac,"SD14x08Tama-VLP,TSn-CS-v06.","A 1-shot sample taken of a 14-inch diameter, 8...",144719,quartertone,https://freesound.org/s/144719/,https://creativecommons.org/licenses/by/4.0/
516885,test/475963.flac,breathehope - kitchen - 09.,From my Kitchen.,2135,smallsushi,https://freesound.org/s/2135/,http://creativecommons.org/licenses/sampling+/...
516886,test/506032.flac,Tham B 048.,Recording of a single stroke 'Tham' played on ...,224741,akshaylaya,https://freesound.org/s/224741/,http://creativecommons.org/licenses/by-nc/3.0/

In [4]:
llm_ready_desc = laion_metadata["caption1"] + "; " + laion_metadata["caption2"]
llm_ready_desc

0         small group laugh 6.; A group of about twenty ...
1                            mushroom disco 2.; weird loop.
2         Page Turn 24.; 31/36 of Various Book manipulat...
3         yawn soft.; Recording of a male yawn with a zo...
4         Fender Chroma Polaris - Mourning - D5 (Mournin...
                                ...
516882    Eastbay-C-504R.; Made with music program, fun ...
516883    amazed 0 30q.; Typical movie-sound to provide ...
516884    SD14x08Tama-VLP,TSn-CS-v06.; A 1-shot sample t...
516885        breathehope - kitchen - 09.; From my Kitchen.
516886    Tham B 048.; Recording of a single stroke 'Tha...
Length: 516887, dtype: object

In [ ]:
import requests
import multiprocessing as mp
from rich.progress import track

laion_metadata["llm_ready_desc"] = llm_ready_desc
prompt_question = (
    "Does the recording description '{}' probably describe a non-instrumental, abstract sound effect?"
    " Exclude descriptions of loops or raw recordings, I'm interested only in synthetic SFX-style sounds."
)
prompt_template = prompt_question + " Answer only with a literal 'yes' or 'no', no other symbols."

def _classify_description(s: str) -> str:
    res = requests.post(
        ollama_api,
        json={
            "model": "qwen2.5:14b",
            "prompt": prompt_template.format(s),
            "think": False,
            "stream": False,
        },
    )
    res_string = res.json()["response"]
    match res_string:
        case "yes" | "Yes":
            return True
        case "no" | "No":
            return False
        case _:
            print(f"got unexpected response: {res_string}")
            return False

# laion_metadata[prompt_question] = laion_metadata["llm_ready_desc"].apply(_classify_description)
laion_subset = laion_metadata.head(1000)
with mp.Pool(8) as pool:
    results = list(track(pool.imap(_classify_description, laion_subset["llm_ready_desc"].values, chunksize=64), total=len(laion_subset)))
laion_subset[prompt_question] = results
laion_subset

Output()

/tmp/ipykernel_3785340/111663702.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  laion_subset[prompt_question] = results

,audio_filename,caption1,caption2,freesound_id,username,freesound_url,license,llm_ready_desc,"Does the recording description '{}' probably describe a non-instrumental, abstract sound effect? Exclude descriptions of loops or raw recordings, I'm interested only in synthetic SFX-style sounds."
0,train/91671.flac,small group laugh 6.,A group of about twenty people laughing during...,30043,tim.kahn,https://freesound.org/s/30043/,https://creativecommons.org/licenses/by/4.0/,small group laugh 6.; A group of about twenty ...,False
1,train/102050.flac,mushroom disco 2.,weird loop.,103163,fons,https://freesound.org/s/103163/,http://creativecommons.org/publicdomain/zero/1.0/,mushroom disco 2.; weird loop.,True
2,train/247195.flac,Page Turn 24.,31/36 of Various Book manipulations.,20258,Koops,https://freesound.org/s/20258/,https://creativecommons.org/licenses/by/4.0/,Page Turn 24.; 31/36 of Various Book manipulat...,False
3,train/352235.flac,yawn soft.,Recording of a male yawn with a zoom H6 in a s...,404384,EskimoNeil,https://freesound.org/s/404384/,http://creativecommons.org/licenses/by-nc/3.0/,yawn soft.; Recording of a male yawn with a zo...,False
4,train/457574.flac,Fender Chroma Polaris - Mourning - D5 (Mournin...,Single note sampled from an analog synthesizer...,289166,modularsamples,https://freesound.org/s/289166/,http://creativecommons.org/publicdomain/zero/1.0/,Fender Chroma Polaris - Mourning - D5 (Mournin...,False
...,...,...,...,...,...,...,...,...,...
995,train/126626.flac,MSfxP10 - 86 3 - (Synth Loop - 102.520 BPM).,This sound or collaborations of other sounds w...,586814,Erokia,https://freesound.org/s/586814/,https://creativecommons.org/licenses/by-nc/4.0/,MSfxP10 - 86 3 - (Synth Loop - 102.520 BPM).;...,False
996,train/351326.flac,Fire Fuse Ignite Flame.,Hello and welcome everyone from Istanbul.,540828,EminYILDIRIM,https://freesound.org/s/540828/,https://creativecommons.org/licenses/by/4.0/,Fire Fuse Ignite Flame.; Hello and welcome eve...,False
997,train/369616.flac,btn068.,Short swish button sound.,28878,junggle,https://freesound.org/s/28878/,https://creativecommons.org/licenses/by/4.0/,btn068.; Short swish button sound.,False
998,train/459113.flac,SMG Sound Hand Snap 0313670391.,Sound by Stolting Media Group.,600880,stoltingmediagroup,https://freesound.org/s/600880/,https://creativecommons.org/licenses/by/4.0/,SMG Sound Hand Snap 0313670391.; Sound by Sto...,False
999,train/328775.flac,glitch SFX 005.,As all files in this sound pack it is made dig...,108965,Dymewiz,https://freesound.org/s/108965/,http://creativecommons.org/licenses/by/3.0/,glitch SFX 005.; As all files in this sound pa...,True

In [11]:
laion_subset[laion_subset[prompt_question]].sample(20)

,audio_filename,caption1,caption2,freesound_id,username,freesound_url,license,llm_ready_desc,"Does the recording description '{}' probably describe a non-instrumental, abstract sound effect? Exclude descriptions of loops or raw recordings, I'm interested only in synthetic SFX-style sounds."
75,train/135505.flac,LargeInsectDrone2.,An unusual but synthetic sound intending to ca...,176734,zimbot,https://freesound.org/s/176734/,https://creativecommons.org/licenses/by/4.0/,LargeInsectDrone2.; An unusual but synthetic s...,True
645,train/252470.flac,Attacking robot.,A simple sample throug a lot of processing.,521611,lucas-post,https://freesound.org/s/521611/,https://creativecommons.org/licenses/by/4.0/,Attacking robot.; A simple sample throug a lot...,True
217,train/441846.flac,Button click.,Intense button clicking sound.,629020,Kolombooo,https://freesound.org/s/629020/,http://creativecommons.org/publicdomain/zero/1.0/,Button click.; Intense button clicking sound.,True
404,train/142656.flac,BrokenBone.,Just a few free sound mixed up and brought to ...,443288,Deathscyp,https://freesound.org/s/443288/,http://creativecommons.org/publicdomain/zero/1.0/,BrokenBone.; Just a few free sound mixed up an...,True
659,train/7130.flac,suspencechase.,Another batch of space sounds more suitable fo...,55565,NoiseCollector,https://freesound.org/s/55565/,http://creativecommons.org/licenses/by/3.0/,suspencechase.; Another batch of space sounds ...,True
953,train/363683.flac,MSfxP2 - 352.,This sound or sounds was created through the h...,481477,Erokia,https://freesound.org/s/481477/,https://creativecommons.org/licenses/by-nc/4.0/,MSfxP2 - 352.; This sound or sounds was create...,True
123,train/341542.flac,Humanatone 37.,"rising formant puff, ~700hz.",608011,Department64,https://freesound.org/s/608011/,https://creativecommons.org/licenses/by/4.0/,"Humanatone 37.; rising formant puff, ~700hz.",True
198,train/387157.flac,Türsummer - kurz einmal.,"Sound of door buzzer, only one time and short.",489506,BockelSound,https://freesound.org/s/489506/,https://creativecommons.org/licenses/by/4.0/,Türsummer - kurz einmal.; Sound of door buzzer...,True
700,train/57150.flac,MSfxP4 - 11 4.,This sound or sounds was created through the h...,490436,Erokia,https://freesound.org/s/490436/,https://creativecommons.org/licenses/by-nc/4.0/,MSfxP4 - 11 4.; This sound or sounds was creat...,True
868,train/141327.flac,Weird Grunt.,Grunt of a weird creature.,521951,Kastenfrosch,https://freesound.org/s/521951/,http://creativecommons.org/publicdomain/zero/1.0/,Weird Grunt.; Grunt of a weird creature.,True
582,train/115100.flac,Tiny Thin Soft Close 04.,The recordings found in this foley pack are al...,551906,Joao_Janz,https://freesound.org/s/551906/,http://creativecommons.org/publicdomain/zero/1.0/,Tiny Thin Soft Close 04.; The recordings found...,True
243,train/171477.flac,Stöhnen.,Lightweight growl of a dragon or monster etc.,333469,Jeffreys2,https://freesound.org/s/333469/,http://creativecommons.org/publicdomain/zero/1.0/,Stöhnen.; Lightweight growl of a dragon or mon...,True
511,train/252175.flac,Reverse reverb3.,Processed speech fragment with reverse reverb ...,191773,wordswar,https://freesound.org/s/191773/,http://creativecommons.org/licenses/by/3.0/,Reverse reverb3.; Processed speech fragment wi...,True
38,train/126584.flac,Cuerpos2.,choque de cuerpos.,410272,Eliz11,https://freesound.org/s/410272/,http://creativecommons.org/licenses/by-nc/3.0/,Cuerpos2.; choque de cuerpos.,True
580,train/289192.flac,cloche2 spexis.,it's a sound made with my mouth.,2174,spexis,https://freesound.org/s/2174/,http://creativecommons.org/licenses/sampling+/...,cloche2 spexis.; it's a sound made with my mouth.,True
474,train/48723.flac,bridge.,"Synthesized, sound of a medieval castle's draw...",55820,Sergenious,https://freesound.org/s/55820/,https://creativecommons.org/licenses/by/4.0/,"bridge.; Synthesized, sound of a medieval cast...",True
882,train/215645.flac,Rummaging through Pockets 2.,The sound of someone rummaging through a pocke...,416287,Fugeni,https://freesound.org/s/416287/,http://creativecommons.org/publicdomain/zero/1.0/,Rummaging through Pockets 2.; The sound of som...,True
820,train/269315.flac,"Elevator ascending two floors, peaking on door...",Elevator ascending two floors.,77785,tsbertalan,https://freesound.org/s/77785/,http://creativecommons.org/publicdomain/zero/1.0/,"Elevator ascending two floors, peaking on door...",True
202,train/84233.flac,Burp 4.,"A short, intense burp.",399766,tehteho,https://freesound.org/s/399766/,http://creativecommons.org/publicdomain/zero/1.0/,"Burp 4.; A short, intense burp.",True
749,train/228220.flac,MSfxP6 - 73 (Soundscape).,This sound or sounds was created through the h...,510681,Erokia,https://freesound.org/s/510681/,https://creativecommons.org/licenses/by-nc/4.0/,MSfxP6 - 73 (Soundscape).; This sound or sound...,True

# Snares filtering analysis

In [4]:
# laion_qwen25_snares = pd.read_csv("laion_snares.csv")
# laion_metadata["qwen25_is_snare"] = laion_qwen25_snares
# laion_metadata

In [8]:
laion_metadata["qwen25_is_snare"].sum()

23622

In [4]:
import torchaudio as ta
import IPython
from IPython.display import display

# audio_dir = ds_dir / 'audio'

# def display_file(id: str) -> None:
#     audio, sr = ta.load(str(audio_dir / f"{id}.wav"))
#     display(IPython.display.Audio(audio, rate=sr))


# for _, s in labels_df[(labels_df["duration"] >= 0.1) & (labels_df["duration"] <= 0.3)].sample(20).iterrows():
#     print(s["word"], round(s["duration"], 4), s["original_text"])
    # display_file(s['sample_id'])

# laion_metadata[laion_metadata["qwen25_is_snare"]].sample(20)

In [5]:
laion_qwen25_snares = pd.read_csv("laion_snares_qwen25_14b.csv")
laion_metadata["qwen2514b_is_snare"] = laion_qwen25_snares
laion_metadata

,audio_filename,caption1,caption2,freesound_id,username,freesound_url,license,qwen2514b_is_snare
0,train/91671.flac,small group laugh 6.,A group of about twenty people laughing during...,30043,tim.kahn,https://freesound.org/s/30043/,https://creativecommons.org/licenses/by/4.0/,False
1,train/102050.flac,mushroom disco 2.,weird loop.,103163,fons,https://freesound.org/s/103163/,http://creativecommons.org/publicdomain/zero/1.0/,False
2,train/247195.flac,Page Turn 24.,31/36 of Various Book manipulations.,20258,Koops,https://freesound.org/s/20258/,https://creativecommons.org/licenses/by/4.0/,False
3,train/352235.flac,yawn soft.,Recording of a male yawn with a zoom H6 in a s...,404384,EskimoNeil,https://freesound.org/s/404384/,http://creativecommons.org/licenses/by-nc/3.0/,False
4,train/457574.flac,Fender Chroma Polaris - Mourning - D5 (Mournin...,Single note sampled from an analog synthesizer...,289166,modularsamples,https://freesound.org/s/289166/,http://creativecommons.org/publicdomain/zero/1.0/,False
...,...,...,...,...,...,...,...,...
516882,test/464571.flac,Eastbay-C-504R.,"Made with music program, fun to do;).",319481,visual,https://freesound.org/s/319481/,https://creativecommons.org/licenses/by/4.0/,False
516883,test/474610.flac,amazed 0 30q.,Typical movie-sound to provide the short momen...,136402,Setuniman,https://freesound.org/s/136402/,https://creativecommons.org/licenses/by-nc/4.0/,False
516884,test/499425.flac,"SD14x08Tama-VLP,TSn-CS-v06.","A 1-shot sample taken of a 14-inch diameter, 8...",144719,quartertone,https://freesound.org/s/144719/,https://creativecommons.org/licenses/by/4.0/,True
516885,test/475963.flac,breathehope - kitchen - 09.,From my Kitchen.,2135,smallsushi,https://freesound.org/s/2135/,http://creativecommons.org/licenses/sampling+/...,False
516886,test/506032.flac,Tham B 048.,Recording of a single stroke 'Tham' played on ...,224741,akshaylaya,https://freesound.org/s/224741/,http://creativecommons.org/licenses/by-nc/3.0/,False

In [6]:
laion_metadata["qwen2514b_is_snare"].sum()

8560

In [7]:
laion_metadata[laion_metadata["qwen2514b_is_snare"]].sample(20)

,audio_filename,caption1,caption2,freesound_id,username,freesound_url,license,qwen2514b_is_snare
243093,train/454290.flac,DR Snare 039.,DR Snare 039 //cc0.,577134,deadrobotmusic,https://freesound.org/s/577134/,http://creativecommons.org/publicdomain/zero/1.0/,True
463793,train/58466.flac,snare6.,DRM syncussion german analog drum machine filt...,133933,hesed23,https://freesound.org/s/133933/,http://creativecommons.org/licenses/by/3.0/,True
107992,train/378307.flac,snare 3 trr.,"snare, drum kit tama dw ludwig percussion hit ...",209888,Veiler,https://freesound.org/s/209888/,http://creativecommons.org/publicdomain/zero/1.0/,True
1132,train/103801.flac,[SFX] short thick bass sound.,_.,381354,waveplaySFX,https://freesound.org/s/381354/,https://creativecommons.org/licenses/by/4.0/,True
342452,train/305006.flac,PPU-SNARE - Marker #143.,"Heavily processed, strongly compressed, tight ...",208420,crispydinner,https://freesound.org/s/208420/,http://creativecommons.org/publicdomain/zero/1.0/,True
335528,train/205043.flac,"SD14x08Tama-MHP,TSn-CS-v11.","A 1-shot sample taken of a 14-inch diameter, 8...",142766,quartertone,https://freesound.org/s/142766/,https://creativecommons.org/licenses/by/4.0/,True
205025,train/431809.flac,SMG Sound Hand Snap 0698888861.,Sound by Stolting Media Group.,600190,stoltingmediagroup,https://freesound.org/s/600190/,unknown,True
103243,train/189210.flac,"SD14x08Tama-HP,TSn-CS-v03.","A 1-shot sample taken of a 14-inch diameter, 8...",142513,quartertone,https://freesound.org/s/142513/,https://creativecommons.org/licenses/by/4.0/,True
130177,train/122277.flac,SNARE55.,parte de la colección: GALPÓN SAMPLESesta cole...,351024,kaiserd88,https://freesound.org/s/351024/,http://creativecommons.org/publicdomain/zero/1.0/,True
440210,train/449466.flac,electribe-snares slice 67.,these are samples from the new korg electribe ...,260372,soneproject,https://freesound.org/s/260372/,http://creativecommons.org/publicdomain/zero/1.0/,True
142188,train/187111.flac,"SD14x08Tama-MLP,0Sn-HdC-v16.","A 1-shot sample taken of a 14-inch diameter, 8...",143354,quartertone,https://freesound.org/s/143354/,https://creativecommons.org/licenses/by/4.0/,True
330683,train/413963.flac,Table bang.,Bang table sound.,507939,GeorgiaReitano1970,https://freesound.org/s/507939/,http://creativecommons.org/publicdomain/zero/1.0/,True
13373,train/80807.flac,"SD14x08Tama-LP,0Sn-HdE-v16.","A 1-shot sample taken of a 14-inch diameter, 8...",143857,quartertone,https://freesound.org/s/143857/,https://creativecommons.org/licenses/by/4.0/,True
492720,test/472125.flac,SMG Sound Drum Snare 1297763704.,Drum Sound by Stolting Media Group.,598650,stoltingmediagroup,https://freesound.org/s/598650/,https://creativecommons.org/licenses/by/4.0/,True
179630,train/327387.flac,Snare 01.,decided to share some of my samples for free.,326588,hardwareshaba,https://freesound.org/s/326588/,http://creativecommons.org/publicdomain/zero/1.0/,True
157658,train/141851.flac,BoxKit Snare 1.,Part of a drum kit made by recording strikes o...,514105,BennDeMole,https://freesound.org/s/514105/,http://creativecommons.org/licenses/by/3.0/,True
144789,train/237942.flac,Snare sample - 2015 - 7 Punch.,Snare_sample_-_2015_-_7_Punch.,269742,Theriavirra,https://freesound.org/s/269742/,http://creativecommons.org/licenses/by/3.0/,True
59839,train/381924.flac,SMG Sound Drum Snare 1607081517.,Drum Sound by Stolting Media Group.,598743,stoltingmediagroup,https://freesound.org/s/598743/,https://creativecommons.org/licenses/by/4.0/,True
260212,train/106359.flac,sy 43.,Here's a heap of snapshot samples of the Synar...,135216,thebrightside,https://freesound.org/s/135216/,http://creativecommons.org/publicdomain/zero/1.0/,True
258962,train/353205.flac,35-Golpe mesa.,Un golpe a una mesa.,491897,LordFrodo10,https://freesound.org/s/491897/,http://creativecommons.org/publicdomain/zero/1.0/,True

In [8]:
laion_metadata[laion_metadata["qwen2514b_is_snare"]].to_csv("laion_qwen25_14b_snares_metadata.csv", index_label="original_index")

# SFX v1 filtering analysis

In [1]:
import pandas as pd

laion_metadata = pd.read_csv("freesound_meta.csv")
laion_qwen25_is_sfx = pd.read_csv("laion_sfx_qwen25_14b.csv")
laion_metadata["is_sfx"] = laion_qwen25_is_sfx
laion_sfx = laion_metadata[laion_metadata["is_sfx"]]
laion_sfx

,audio_filename,caption1,caption2,freesound_id,username,freesound_url,license,is_sfx
5,train/259853.flac,Krg T spam c 5.,"SSA - 'Synthesis , Sampler , Acoustic' sample ...",317894,deleted_user_2195044,https://freesound.org/s/317894/,unknown,True
11,train/224417.flac,Analog Noise.,cranked up resonance+LFO from the elektron ana...,528458,gigala,https://freesound.org/s/528458/,http://creativecommons.org/publicdomain/zero/1.0/,True
20,train/27353.flac,Menu UI Click 4.,A major collective of sounds I created for the...,470221,Erokia,https://freesound.org/s/470221/,https://creativecommons.org/licenses/by/4.0/,True
36,train/206808.flac,SFX SQUELCH release short 18.,One of a series of recordings of a delightfull...,589506,MrFossy,https://freesound.org/s/589506/,unknown,True
40,train/437133.flac,Muffled Hit Claps.,A series of muffled hits made with my hands cl...,444766,AO-SoundPawz,https://freesound.org/s/444766/,http://creativecommons.org/publicdomain/zero/1.0/,True
...,...,...,...,...,...,...,...,...
516838,test/469198.flac,Scary laugh.,Me laughing with audacity effects.,275997,Creeper_Ciller78,https://freesound.org/s/275997/,http://creativecommons.org/licenses/by/3.0/,True
516845,test/491092.flac,PS002LC 108.,Original sounds specially made to people who n...,576468,lcscrts,https://freesound.org/s/576468/,http://creativecommons.org/publicdomain/zero/1.0/,True
516848,test/466971.flac,breath exhaled1.,Having fun with Spectrasonics Atmosphere plugi...,60886,alextundra,https://freesound.org/s/60886/,http://creativecommons.org/licenses/by/3.0/,True
516849,test/508096.flac,u.,Very short noises created by converting images...,254249,kwahmah_02,https://freesound.org/s/254249/,http://creativecommons.org/licenses/by/3.0/,True
516883,test/474610.flac,amazed 0 30q.,Typical movie-sound to provide the short momen...,136402,Setuniman,https://freesound.org/s/136402/,https://creativecommons.org/licenses/by-nc/4.0/,True

In [9]:
for d in laion_sfx.sample(20)["caption2"].values:
    print(d)

White noise processed with a descending bandpass filter.
granular structure, filtered.
short bitcrushed sound effect distorted for whatever use.
SSA - 'Synthesis , Sampler , Acoustic' sample pack include 217 Wav files (Sounds) , Generated with Synths like: Vaccum , Subtractor , Korg mashines , and others , also Db33 - Organ , free recorded Vocals and electronnic drums.
"glitch loop processed with plugins".
How i imagine a tree sounds when he tries to tell you about his situation.
Jump SFX / 8bit.
New laughs for this years Halloween!.
By phasing a normal radio static noise, I made this strange sound.
Ear Ringing Noise!.
Sound of a man quickly laughing, useful for horror ambiance.
This sound or sounds was created through the help of VST's, time shifting, parametric EQ, cutting, sampling, layering and many other methods of sound manipulation.
An atmospheric / ambient sound that might sit well within a film, animation or computer game.
vocal syllables, created by recording somewhat rhythmic nonesense talk with an SM-58, followed by automated segmentation of the audio.
sound synthesis made from ChucK programming language.
Short button click sound.
Session 01 - Freestyle FX - samples made with my own voice using manipulator and vocalizer pro.
Another weird sound made by "wah wah-ing" and echoing Audacity's noise choices.
Some really dry leaves and flowers in a vase being crunched up a bit.
Human imitating cat's meowing.